version: '3.1'

services:
    mysql:
        image: 'mysql:5.7'
        working_dir: /application
        volumes:
            - './dbdata:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=transaction
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=password
        ports:
            - '42001:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './api:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - './api:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'